### ISSUE TITLE
AivenApplication owned by NaisJob is requeued ad infinitum

### ISSUE THREAD

**Issue by tronghn** [nais/aivenator#59]
Currently, if an AivenApplication does not have any associated ReplicaSets, we set an empty/dummy OwnerReference for the associated Secret:

https://github.com/nais/aivenator/blob/1f00c8a03f5cfece1b97e294a27f04e082c523b5/pkg/handlers/secret/secret.go#L45-L54

The OwnerReferences for the Secret are checked during reconciliation:

https://github.com/nais/aivenator/blob/06908b57662b4c6f6fe3670f8be8593c0313e620/controllers/aiven_application/reconciler.go#L384-L408

and the AivenApplication is ultimately requeued none of them match the expected Kind:

https://github.com/nais/aivenator/blob/06908b57662b4c6f6fe3670f8be8593c0313e620/controllers/aiven_application/reconciler.go#L181-L188

This works as intended for Applications that spawn Deployments (and in turn ReplicaSets), where we want to eventually find and assign a matching ReplicaSet.

However, in the case of NaisJobs - this does not work as intended as there is never a Job nor a CronJob being assigned to the Secret's OwnerReferences - and will thus result in the AivenApplication being requeued for processing again and again. 

This isn't a huge problem as there shouldn't be any changes in the Secret data between each reconciliation where the AivenApplication generation is unchanged, but we should handle it properly for NaisJobs (Jobs and CronJobs) as well.

**Comment by mortenlj** [comment]
https://github.com/nais/aivenator/pull/60

**Comment by mortenlj** [comment]
Fixed in #60
