### ISSUE TITLE
Gjøre tiltak for å motvirke økningen i Aiven Kafka serviceusers

### ISSUE THREAD

**Issue by mortenlj** [nais/aivenator#66]
Vi har sett en markant økning i antallet Kafka serviceusers i nav-dev, sånn at vi har måttet be Aiven om å øke grensene to ganger siden rett før jul.

Det virker litt rart at det skal øke så mye, og bare i dev, så vi bør undersøke om det er noe som ikke er helt riktig.

Aiven etterlyser også om vi har noen anelse om hva vi kommer til å trenge på sikt, og det hadde nok vært lurt om vi tok et steg tilbake og tenkte gjennom hva vi tror er riktig behov her. Spesielt siden vi har begynt å se performance problemene Aiven påpeker hver gang vi ber dem øke grensen.

Grensene er per i dag 1000 i nav-prod, og 2500 i nav-dev.

**Comment by sechmann** [comment]
1500 i bruk i nav-prod i dag, bedt om ny økning

**Comment by jhrv** [comment]
Se på alternativ løsning der vi roterer ikke pr deploy ukritisk, men om den ikke er rotert ila siste X dager?

**Comment by sechmann** [comment]
Slik som det er gjort i Azurerator høres ut som en løsning med grei virk - @tronghn kan sikkert ta en TLDR på det.

**Comment by tronghn** [comment]
tl;dr for azurerator:

- naiserator setter secretName for azureapp-ressurser som har en suffiks med år og ukenummer, dvs. at secretName maksimalt kun endrer seg en gang i uka ved deploy
- azurerator roterer kun secrets hvis secretName har endret seg

**Comment by mortenlj** [comment]
Jeg har tenkt litt på dette i dag, og er usikker på om det er nevneverdig effekt å hente her.

I dag har i praksis alle apper 3 servicebrukere, knyttet til de siste tre deploys.

Med et nytt opplegg ala det azurerator har, med ny secret hver uke, så vil vi få noe slikt:
* De som deployer mer enn 3 ganger i uka, vil ha 1 servicebruker i deler av uken, men vil ha 2 servicebrukere i ukesovergangen
* Alle andre vil veldig lett havne på 3 servicebrukere mesteparten av tiden

Samtidig tror jeg implementasjonen er superlett, så kanskje verdt det uansett. 🤷

**Comment by jhrv** [comment]
Var ikke også noe av utgangspunktet for issuet også at resync av apper (som vi av og til må) fører til en stor økning sa'er - som løses med azureator tilnærmingen?

**Comment by mortenlj** [comment]
Det løses vel ikke i utgangspunktet annet enn for apper som allerede har blitt deployet denne uka. Så på mandager har det neppe noe å si, på fredager er det kanskje en merkbar forbedring. Kommer an på hvor mange av appene som deployes hver uke ... :shrug: 

Men som sagt, superlett implementasjon tror jeg, så kan være vi bare skal gjøre det uansett.

**Comment by mortenlj** [comment]
> Hva skal endres i `dashboards`?

Tror ikke det er noe å endre i dashboards lenger, vi har ikke lagt inn thresholds i det nye dashboardet.

**Comment by mortenlj** [comment]
Etter mye omskriving er dette nå ganske klart. Nødvendige endringer i Aivenator er på plass, og virker både med secrets per deploy slik det er nå, og tilsynelatende med secrets per uke.

Secrets per uke er implementert i naiserator, bak et feature-flagg. Dette flagget er skrudd på i dev-nais-dev, og ser ut til å fungere fint, men er nok best å la det gå over en uke for å se at overgangen også fungerer som ønsket før vi skrur på flagget andre steder.

Flagget i naiserator heter "aiven-shared-secrets".

**Comment by mortenlj** [comment]
Skrudd på flagget globalt i fasit. Tenker vi lar det stå slik en stund, og hvis alt fungerer fint så endrer vi chart default til true.
